//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetC4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class C4ModelContainer : DbContext
    {
        public C4ModelContainer()
            : base("name=C4ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employee> ListEmployee { get; set; }
        public DbSet<Center> ListCenter { get; set; }
        public DbSet<Gdz> ListGdz { get; set; }
        public DbSet<Package> ListPackage { get; set; }
        public DbSet<Route> ListRoute { get; set; }
        public DbSet<Stage> ListStage { get; set; }
        public DbSet<Vehicle> ListVehicle { get; set; }
        public DbSet<Slot> ListSlot { get; set; }
    }
}
