//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        public Center()
        {
            this.ListSlot = new HashSet<Slot>();
            this.ListVehicle = new HashSet<Vehicle>();
        }
    
        public int Code { get; set; }
        public string Name { get; set; }
        public System.Data.Spatial.DbGeography Location { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
        public string Group { get; set; }
    
        public virtual ICollection<Slot> ListSlot { get; set; }
        public virtual ICollection<Vehicle> ListVehicle { get; set; }
    }
}
