//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gdz
    {
        public Gdz()
        {
            this.ListVehicle = new HashSet<Vehicle>();
        }
    
        public int ID { get; set; }
        public System.Data.Spatial.DbGeography Coordinates { get; set; }
    
        public virtual ICollection<Vehicle> ListVehicle { get; set; }
    }
}
