//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public Slot()
        {
            this.ListPackage = new HashSet<Package>();
        }
    
        public int Code { get; set; }
        public int MaxCapacity { get; set; }
        public int FreeCapacity { get; set; }
        public int Center_Code { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
        public virtual Center Center { get; set; }
        public virtual ICollection<Package> ListPackage { get; set; }
    }
}
