//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int ID { get; set; }
        public string Number { get; set; }
    
        public virtual Gdz Gdz { get; set; }
        public virtual Slot Slot { get; set; }
        public virtual Center Center { get; set; }
    }
}
